In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import scipy
import sklearn
%matplotlib inline

In [2]:
from tensorflow import keras
from keras.datasets import mnist

(xTrain, yTrain), (xTest, yTest) = mnist.load_data()

shuffle_index = np.random.permutation(60000)
xTrain,yTrain = xTrain[shuffle_index], yTrain[shuffle_index]
xTrain = xTrain.reshape(60000, 784)
xTest = xTest.reshape(10000, 784)

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

myPipeline = Pipeline([
    ("stdScaler", StandardScaler())
])

In [9]:
from sklearn.neighbors import KNeighborsClassifier

standardized_xTrain = myPipeline.fit_transform(xTrain)
myKNN = KNeighborsClassifier()
myKNN.fit(standardized_xTrain, yTrain)


5


In [15]:
from sklearn.metrics import roc_curve
from sklearn.model_selection import cross_val_score, cross_val_predict

yScore = myKNN.predict_proba(standardized_xTrain)
print(yScore)


[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [23]:
from sklearn.metrics import f1_score

scores = cross_val_predict(myKNN, standardized_xTrain, yTrain, cv=3)

In [28]:
F1Scores = f1_score(yTrain, scores, average="weighted")
print(F1Scores)
myKNN.get_params()

0.9408227526721615


{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [35]:
from sklearn.model_selection import GridSearchCV

myGrid = GridSearchCV(myKNN,
param_grid=[
    {"n_neighbors": [4,5,6,7,8]},
    {"weights": ["uniform", "distance"]}
])
myGrid.fit(standardized_xTrain, yTrain)


GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': [4, 5, 6, 7, 8]},
                         {'weights': ['uniform', 'distance']}])

In [36]:
myGrid.get_params()

{'cv': None,
 'error_score': nan,
 'estimator__algorithm': 'auto',
 'estimator__leaf_size': 30,
 'estimator__metric': 'minkowski',
 'estimator__metric_params': None,
 'estimator__n_jobs': None,
 'estimator__n_neighbors': 5,
 'estimator__p': 2,
 'estimator__weights': 'uniform',
 'estimator': KNeighborsClassifier(),
 'n_jobs': None,
 'param_grid': [{'n_neighbors': [4, 5, 6, 7, 8]},
  {'weights': ['uniform', 'distance']}],
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': None,
 'verbose': 0}